# Multi-Agent Orchestrator 配置
# 本地化多代理編排系統

# 🎯 通用設置
ORCHESTRATOR_VERSION="1.0.0"
ORCHESTRATOR_LOG_LEVEL="info"  # debug, info, warn, error
ORCHESTRATOR_ENABLE_LOGGING=true

# 🤖 預設模型
# PLANNER 使用深度分析
ORCHESTRATOR_PLANNER_MODEL="zai/glm-5"

# ARTIFICER 使用標準編碼
ORCHESTRATOR_ARTIFICER_MODEL="zai/glm-5"

# SCOUT 使用快速搜尋
ORCHESTRATOR_SCOUT_MODEL="minimax/MiniMax-M2.1"

# INQUISITOR 使用安全審計
ORCHESTRATOR_INQUISITOR_MODEL="zai/glm-5"

# LOGISTICS 使用輕量處理
ORCHESTRATOR_LOGISTICS_MODEL="minimax/MiniMax-M2.1"

# 🔀 路由配置
ROUTING_AUTO_ENABLE=true
ROUTING_KEYWORD_MATCH=true
ROUTING_FUZZY_MATCH=false

# 📊 PLANNER 配置
PLANNER_YOUTUBE_ANALYTICS_ENABLED=true
PLANNER_INCOME_TRACKER_ENABLED=true
PLANNER_CONTENT_CREATOR_ENABLED=true

# 🔧 ARTIFICER 配置
ARTIFICER_GITHUB_ENABLED=true
ARTIFICER_GIT_AUTOMATION_ENABLED=true
ARTIFICER_APP_SCAFFOLD_ENABLED=true
ARTIFICER_VIDEO_SCRIPT_ENABLED=true
ARTIFICER_THUMBNAIL_ENABLED=true

# 🔍 SCOUT 配置
SCOUT_DDG_SEARCH_ENABLED=true
SCOUT_SKILL_SCANNER_ENABLED=true
SCOUT_DATA_ANALYZER_ENABLED=true

# 🛡️ INQUISITOR 配置
INQUISITOR_SECURITY_AUDIT_ENABLED=true
INQUISITOR_API_SECURITY_ENABLED=true
INQUISITOR_SYSTEM_MONITOR_ENABLED=true

# 📦 LOGISTICS 配置
LOGISTICS_CRON_ENABLED=true
LOGISTICS_BACKUP_ENABLED=true
LOGISTICS_WORKFLOW_ENABLED=true

# ⚡ 工作流配置
WORKFLOW_DEFAULT_TIMEOUT=300  # 秒
WORKFLOW_MAX_RETRIES=3
WORKFLOW_RETRY_DELAY=5  # 秒

# 📋 日誌配置
LOG_DIR="$HOME/.openclaw/logs/orchestrator"
LOG_FILE="orchestrator.log"
LOG_ROTATION_SIZE="10M"
LOG_ROTATION_COUNT=5

# 🔒 安全配置
SECURITY_REQUIRE_CONFIRMATION=true
SECURITY_BLOCK_DANGEROUS_COMMANDS=true
