#!/usr/bin/env python3
"""
Weekly Report Generator
自动生成周报
"""

import json
import sys
from datetime import datetime, timedelta
from pathlib import Path
from collections import defaultdict

WORKSPACE_PATH = Path(__file__).parent.parent
L1_DAILY_PATH = WORKSPACE_PATH / "memory" / "L1-daily"
L2_WEEKLY_PATH = WORKSPACE_PATH / "memory" / "L2-weekly"


def get_week_bounds(date=None):
    """获取本周的开始和结束日期"""
    if date is None:
        date = datetime.now()

    # 本周开始（周一）
    week_start = date - timedelta(days=date.weekday())
    week_end = week_start + timedelta(days=6)

    return week_start.date(), week_end.date()


def scan_daily_logs(week_start, week_end):
    """扫描本周的每日日志"""
    logs = []

    current_date = week_start
    while current_date <= week_end:
        log_file = L1_DAILY_PATH / f"{current_date}.md"

        if log_file.exists():
            with open(log_file, 'r', encoding='utf-8') as f:
                content = f.read()
                logs.append({
                    "date": str(current_date),
                    "content": content,
                    "file": str(log_file)
                })

        current_date += timedelta(days=1)

    return logs


def extract_stats(logs):
    """从日志中提取统计数据"""
    stats = {
        "total_days": len(logs),
        "tasks_completed": 0,
        "files_created": 0,
        "git_commits": 0,
        "projects_advanced": [],
        "skills_used": set(),
        "token_savings": 0
    }

    for log in logs:
        content = log["content"].lower()

        # 统计完成的任务
        if "✅" in content:
            stats["tasks_completed"] += content.count("✅")

        # 统计文件创建
        if "create" in content or "新建" in content or "add" in content:
            stats["files_created"] += 1

        # 统计 git commits
        if "commit" in content:
            stats["git_commits"] += 1

        # 统计项目推进
        if "phase" in content or "完成" in content:
            # 提取项目名称（简化版）
            pass

        # 统计技能使用
        skills_keywords = ["youtube", "stock", "xiaohongshu", "mcp", "token"]
        for skill in skills_keywords:
            if skill in content:
                stats["skills_used"].add(skill)

        # 统计 token 节省
        if "token" in content and "saving" in content:
            # 提取节省百分比（简化版）
            pass

    stats["skills_used"] = list(stats["skills_used"])
    return stats


def generate_weekly_report(week_start, week_end, stats, logs):
    """生成周报"""
    week_num = datetime.now().isocalendar()[1]
    year = datetime.now().year

    report_lines = [
        f"# 周报 {year}-W{week_num}",
        "",
        f"> **时间范围**: {week_start} 至 {week_end}",
        f"> **生成时间**: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "---",
        "",
        "## 📊 本周概况",
        "",
        f"**活跃天数**: {stats['total_days']} 天",
        f"**完成任务**: {stats['tasks_completed']} 个",
        f"**创建文件**: {stats['files_created']} 个",
        f"**Git Commits**: {stats['git_commits']} 次",
        "",
        "---",
        "",
        "## 🎯 主要成果",
        ""
    ]

    # 从日志中提取主要成果
    achievements = []
    for log in logs:
        lines = log["content"].split("\n")
        for line in lines:
            if "✅" in line and len(line) > 10:
                achievements.append(f"- [{log['date']}] {line.strip()}")

    if achievements:
        report_lines.extend(achievements[:10])  # 最多显示 10 个
    else:
        report_lines.append("- 暂无记录")

    report_lines.extend([
        "",
        "---",
        "",
        "## 🛠️ 使用技能",
        ""
    ])

    if stats["skills_used"]:
        for skill in stats["skills_used"]:
            report_lines.append(f"- {skill}")
    else:
        report_lines.append("- 暂无记录")

    report_lines.extend([
        "",
        "---",
        "",
        "## 📈 下周计划",
        "",
        "- [ ] 继续推进 MCP Phase 2",
        "- [ ] 史莱姆系统视觉化",
        "- [ ] Token Saver 全面整合",
        "- [ ] 收入渠道启动",
        "",
        "---",
        "",
        f"*Generated by Ken AI Assistant on {datetime.now().strftime('%Y-%m-%d %H:%M')}*"
    ])

    return "\n".join(report_lines)


def main():
    """主程序"""
    print("📊 周报生成器")
    print("=" * 60)

    # 获取本周时间范围
    week_start, week_end = get_week_bounds()
    print(f"📅 本周范围: {week_start} 至 {week_end}")

    # 扫描日志
    print("🔍 扫描每日日志...")
    logs = scan_daily_logs(week_start, week_end)
    print(f"✅ 找到 {len(logs)} 天的日志")

    if not logs:
        print("⚠️  本周暂无日志")
        return

    # 提取统计
    print("📊 提取统计数据...")
    stats = extract_stats(logs)

    print(f"  活跃天数: {stats['total_days']}")
    print(f"  完成任务: {stats['tasks_completed']}")
    print(f"  Git commits: {stats['git_commits']}")

    # 生成周报
    print("\n📝 生成周报...")
    report = generate_weekly_report(week_start, week_end, stats, logs)

    # 保存周报
    week_num = datetime.now().isocalendar()[1]
    year = datetime.now().year
    output_file = L2_WEEKLY_PATH / f"{year}-W{week_num}.md"

    L2_WEEKLY_PATH.mkdir(parents=True, exist_ok=True)

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(report)

    print(f"✅ 周报已保存: {output_file}")

    # 显示预览
    print("\n" + "=" * 60)
    print("📄 周报预览:")
    print("=" * 60)
    print(report[:500] + "..." if len(report) > 500 else report)


if __name__ == "__main__":
    main()
